### PR TITLE
Handle player names containing spaces in discord webhook script

### PR DESCRIPTION
**Pull request by jared-hess**

### CODE REVIEW

**Comment by TapeWerm** [comment]
I did not know gamertags could have spaces until this pull request. As an Xbox owner I am an embarrassment to my own kind. Thank you, and please update MCscripts. I just worked around an issue with systemd stopping the mcbe's stdin socket before MCstop stops the server. It's sporadic and only seems to happen if the server has been running for more than 75 minutes, but it did make the autoupdate script fail for me. [DisableServices.sh](https://github.com/TapeWerm/MCscripts/blob/master/DisableServices.sh) will tell you to enable `mcbe@MCBE.socket` now that that's separate from the service.

**Comment by TapeWerm** [comment]
lol I did `git pull` instead of `git fetch; git rebase origin/master`. Hopefully that doesn't cause any issues pulling the latest commits for you, I think it just looks out of order in `git log`?

**Comment by jared-hess** [comment]
Haha, no worries, it's easy to miss. Though honestly I'm a little surprised nobody else noticed before now.
Good to hear you found a workaround for those systemd issues.

**Comment by TapeWerm** [comment]
I also noticed this afternoon that systemd kills the bedrock_server process before it finishes stopping most of the time. I always wondered why it took so long for the client to notice the server was down, it's because unless you set `KillMode=none` bedrock_server will get a SIGTERM right after MCstop.sh echo's `stop` into bedrock_server's stdin. Usually the server is not done stopping by the time it gets the SIGTERM. Many things I didn't realize until now.

**Pull request merged**
